[tasks.build-wasm]
script = """
cargo build --target wasm32-unknown-unknown
wasm-bindgen ../target/wasm32-unknown-unknown/debug/rust_webgl_bin.wasm --out-dir dist --target web
"""

[tasks.serve]
command = "basic-http-server"
args = ["-x", "./dist"]
